replicaCount: 0

image:
  repository: selcdcommonacr.azurecr.io/selfcaredashboardbackend

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://imprese.dev.notifichedigitali.it,https://api-pnpg.dev.selfcare.pagopa.it,https://pnpg.dev.selfcare.pagopa.it,http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:3003"
  tls:
    - hosts:
        - dev01.pnpg.internal.dev.selfcare.pagopa.it
      secretName: dev01-pnpg-internal-dev-selfcare-pagopa-it
  hosts:
    - host: "dev01.pnpg.internal.dev.selfcare.pagopa.it"
      paths:
        - path: /dashboard/(.*)
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 0
  maxReplicas: 0
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  B4F_DASHBOARD_LOG_LEVEL: "DEBUG"
  REST_CLIENT_LOGGER_LEVEL: "FULL"
  JWT_TOKEN_EXCHANGE_ISSUER: "https://pnpg.dev.selfcare.pagopa.it"
  PUBLIC_FILE_STORAGE_BASE_URL: "https://selcdweupnpgcheckoutsa.z6.web.core.windows.net"
  JWT_ISSUER: "https://hub-login.spid.dev.pn.pagopa.it"
  SELFCARE_USER_URL: "https://selc-d-pnpg-user-ms-ca.livelydesert-633675bb.westeurope.azurecontainerapps.io"
