image:
  repository: selcpcommonacr.azurecr.io/selfcaredashboardbackend
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://imprese.notifichedigitali.it,https://api-pnpg.selfcare.pagopa.it,https://pnpg.selfcare.pagopa.it"
  tls:
    - hosts:
        - prod01.pnpg.internal.selfcare.pagopa.it
      secretName: prod01-pnpg-internal-selfcare-pagopa-it
  hosts:
    - host: "prod01.pnpg.internal.selfcare.pagopa.it"
      paths:
        - path: /dashboard/v1/(.*)
          pathType: ImplementationSpecific
          
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  B4F_DASHBOARD_LOG_LEVEL: "INFO"
  REST_CLIENT_LOGGER_LEVEL: "BASIC"
  JWT_TOKEN_EXCHANGE_ISSUER: "https://pnpg.selfcare.pagopa.it"
  PUBLIC_FILE_STORAGE_BASE_URL: "https://selcpcheckoutsa.z6.web.core.windows.net"