image:
  repository: selcucommonacr.azurecr.io/selfcaredashboardbackend
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://imprese.uat.notifichedigitali.it,https://api-pnpg.uat.selfcare.pagopa.it,https://pnpg.uat.selfcare.pagopa.it,http://localhost:3000,http://localhost:3001,http://localhost:3002"
  tls:
    - hosts:
        - uat01.pnpg.internal.uat.selfcare.pagopa.it
      secretName: uat01-pnpg-internal-uat-selfcare-pagopa-it
  hosts:
    - host: "uat01.pnpg.internal.uat.selfcare.pagopa.it"
      paths:
        - path: /dashboard/(.*)
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  B4F_DASHBOARD_LOG_LEVEL: "DEBUG"
  REST_CLIENT_LOGGER_LEVEL: "FULL"
  JWT_TOKEN_EXCHANGE_ISSUER: "https://pnpg.uat.selfcare.pagopa.it"
  PUBLIC_FILE_STORAGE_BASE_URL: "https://selcuweupnpgcheckoutsa.z6.web.core.windows.net"
  SELFCARE_USER_URL: "https://selc-u-pnpg-user-ms-ca.gentleflower-c63e62fe.westeurope.azurecontainerapps.io"