server:
  port: ${B4F_DASHBOARD_SERVER_PORT:8080}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      - swaggerEN
      - AzureStorage
  zipkin:
    enabled: false
  sleuth:
    baggage:
      remote-fields: X-Client-Ip
      correlation-fields: X-Client-Ip

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"


logging:
  level:
    it.pagopa.selfcare: ${B4F_DASHBOARD_LOG_LEVEL:DEBUG}
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{traceId:-},%X{spanId:-}] [%X{uid:-},%X{X-Client-Ip:-}]"