server:
  port: ${B4F_DASHBOARD_SERVER_PORT:8080}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable specific-language documentations
      - swaggerEN
#  jackson:
#    default-property-inclusion: NON_NULL
#    serialization.write-dates-as-timestamps: false
#    serialization.fail-on-empty-beans: false
#    deserialization.fail-on-unknown-properties: false
#    visibility.all: NONE
#    visibility.field: ANY

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"


logging:
  level:
    it.pagopa.selfcare.dashboard: ${B4F_DASHBOARD_LOG_LEVEL:DEBUG}