version: '3.8'
services:

  mockserver:
    image: mockserver/mockserver@sha256:adec675a93253dcd503cda331dbc8c88383c1c79ceb2370ec9766ad3f010d255
    ports:
      - '1080:1080'
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/*.json
      - MOCKSERVER_ENABLE_CORS_FOR_API="true"
      - MOCKSERVER_ENABLE_CORS_FOR_ALL_RESPONSES="true"
    volumes:
      - "./integration-test-config/mock:/config"
    networks:
      - develop-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite@sha256:0a47e12e3693483cef5c71f35468b91d751611f172d2f97414e9c69113b106d9
    ports:
      - "10000:10000"
    command: "azurite --blobHost 0.0.0.0 --inMemoryPersistence"
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCD9I1QhZT4gRjAAHEDPazjFIwtg==
    networks:
      - develop-network

  azure-cli:
    build:
      context: "."
      dockerfile: "integration-test-config/azure-cli/Dockerfile-azure-cli"
    depends_on:
      - azurite
    networks:
      - develop-network
    volumes:
      - "./integration-test-config/blobStorageInit/initAzurite.sh:/initAzurite.sh"
      - "./integration-test-config/blobStorageInit/signed_IO_accordo_adesione.pdf:/workspace/signed_IO_accordo_adesione.pdf"
      - "./integration-test-config/blobStorageInit/products.json:/workspace/products.json"
    environment:
      - SELFCARE_INFRA_PRIVATE_ENV=dev

  mongodb:
    image: mongo:latest@sha256:1cb283500219e8fc0b61b328ea5a199a395a753d88b17351c58874fb425223cb
    ports:
      - '27017:27017'
    volumes:
      - "./integration-test-config/db:/docker-entrypoint-initdb.d"
    networks:
      - develop-network

  userms:
    image: ghcr.io/pagopa/selfcare-user-ms:latest@sha256:c61cfc6c5d1e50d2d980e54ca1020c17e1f0c2622df5aa07871aaefe02e81a2e
    pull_policy: always
    ports:
      - '8081:8080'
    env_file:
      - "./src/test/resources/userenv"
    networks:
      - develop-network
    depends_on:
      - mongodb

  onboardingms:
    image: ghcr.io/pagopa/selfcare-onboarding-ms:latest@sha256:cb4f0c2a723fb692da2783f6f6c23d5037636cda4c467f1e9a3ab9c39bd2597c
    pull_policy: always
    ports:
      - '8080:8080'
    env_file:
      - "./src/test/resources/onboardingenv"
    networks:
      - develop-network
    depends_on:
      - mongodb

  institutionms:
    image: ghcr.io/pagopa/selfcare-institution-ms:latest@sha256:6d0aad5954d0903b3b700dcdd4731f6d0b918eae5a04bbb32958f2aba668b0c0
    pull_policy: always
    ports:
      - '8082:8082'
    env_file:
      - "./src/test/resources/institutionenv"
    networks:
      - develop-network
    depends_on:
      - mongodb

  usergroupms:
    image: ghcr.io/pagopa/selfcare-user-group-ms:latest@sha256:5438377ca5197bf4def5fcb1623e78f48c3c0839d972040286eaca073c6513a2
    pull_policy: always
    ports:
      - '8083:8083'
    env_file:
      - "./src/test/resources/usergroupenv"
    networks:
      - develop-network
    depends_on:
      - mongodb

networks:
  develop-network:
    name: selfcare-develop-network

