version: '3.8'
services:

  mockserver:
    image: mockserver/mockserver@sha256:adec675a93253dcd503cda331dbc8c88383c1c79ceb2370ec9766ad3f010d255
    ports:
      - '1080:1080'
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/*.json
      - MOCKSERVER_ENABLE_CORS_FOR_API="true"
      - MOCKSERVER_ENABLE_CORS_FOR_ALL_RESPONSES="true"
    volumes:
      - "./integration-test-config/mock:/config"
    networks:
      - develop-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite@sha256:647c63a91102a9d8e8000aab803436e1fc85fbb285e7ce830a82ee5d6661cf37
    ports:
      - "10000:10000"
    command: "azurite --blobHost 0.0.0.0 --inMemoryPersistence"
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCD9I1QhZT4gRjAAHEDPazjFIwtg==
    networks:
      - develop-network

  azure-cli:
    build:
      context: "."
      dockerfile: "integration-test-config/azure-cli/Dockerfile-azure-cli"
    depends_on:
      - azurite
    networks:
      - develop-network
    volumes:
      - "./integration-test-config/blobStorageInit/initAzurite.sh:/initAzurite.sh"
      - "./integration-test-config/blobStorageInit/signed_IO_accordo_adesione.pdf:/workspace/signed_IO_accordo_adesione.pdf"
      - "./integration-test-config/blobStorageInit/products.json:/workspace/products.json"
    environment:
      - SELFCARE_INFRA_PRIVATE_ENV=dev

  mongodb:
    image: mongo@sha256:1cb283500219e8fc0b61b328ea5a199a395a753d88b17351c58874fb425223cb
    ports:
      - '27017:27017'
    volumes:
      - "./integration-test-config/db:/docker-entrypoint-initdb.d"
    networks:
      - develop-network

  userms:
    image: ghcr.io/pagopa/selfcare-user-ms:latest@sha256:2f9f85ed634f5f3631cb07f9ce5a5c1884c957d4b8c7cf7e5b65087af86e0e41
    pull_policy: always
    platform: linux/amd64
    ports:
      - '8081:8080'
    env_file:
      - "./src/test/resources/userenv"
    networks:
      - develop-network
    depends_on:
      - mongodb

  onboardingms:
    image: ghcr.io/pagopa/selfcare-onboarding-ms:latest@sha256:3cde7bd51567c1478957a8a1a8578f4b1625d5df6ec7155cbc6b4915ce4f66c1
    pull_policy: always
    platform: linux/amd64
    ports:
      - '8080:8080'
    env_file:
      - "./src/test/resources/onboardingenv"
    networks:
      - develop-network
    depends_on:
      - mongodb

  documentms:
    image: ghcr.io/pagopa/selfcare-document-ms:latest@sha256:71fc6db1c734417337c277986dae354c2ed672c8b753dbd71cc6b4e5e999f392
    pull_policy: always
    platform: linux/amd64
    ports:
      - '8086:8080'
    env_file:
      - "./src/test/resources/documentenv"
    networks:
      - develop-network
    depends_on:
      - mongodb

  institutionms:
    image: ghcr.io/pagopa/selfcare-institution-ms:latest@sha256:3a350260028708ab24b90e844413cfcfa20815c5eceb6da29a0dfd5895fdde17
    pull_policy: always
    platform: linux/amd64
    ports:
      - '8082:8082'
    env_file:
      - "./src/test/resources/institutionenv"
    networks:
      - develop-network
    depends_on:
      - mongodb

  usergroupms:
    image: ghcr.io/pagopa/selfcare-user-group-ms:latest@sha256:354b33b4f77b8d3442c3af7b67c5f02b23deceb7be72dbc8aa2261fc4ad0c0aa
    pull_policy: always
    platform: linux/amd64
    ports:
      - '8083:8083'
    env_file:
      - "./src/test/resources/usergroupenv"
    networks:
      - develop-network
    depends_on:
      - mongodb

  iamms:
    image: ghcr.io/pagopa/selfcare-iam-ms:latest@sha256:17b4ea3482275ade026d77ee7fba0fa9ab2c9daac80e0363ce87d62426387e73
    pull_policy: always
    platform: linux/amd64
    ports:
      - '8085:8080'
    env_file:
      - "./src/test/resources/iamenv"
    networks:
      - develop-network
    depends_on:
      - mongodb

networks:
  develop-network:
    name: selfcare-develop-network

