server:
  port: ${B4F_DASHBOARD_SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      - swaggerEN
      - AzureStorage
  zipkin:
    enabled: false
  sleuth:
    baggage:
      remote-fields: X-Client-Ip
      correlation-fields: X-Client-Ip

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"


logging:
  level:
    it.pagopa.selfcare: ${B4F_DASHBOARD_LOG_LEVEL:DEBUG}
  pattern:
    additional-info: ",%X{X-Client-Ip:-}]"

dashboard:
  security:
    connector: ${B4F_DASHBOARD_SECURITY_CONNECTOR:v2}

resilience4j:
  retry:
    retry-aspect-order: 1
    instances:
      retryTimeout:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - feign.RetryableException

feature:
  viewcontract:
    enabled: ${FEATURE_VIEWCONTRACT_ENABLED:false}
