# Primo stage: usiamo un'immagine con git per clonare il repository
FROM alpine/git@sha256:94b40c2135951103e0c5c7db07ae4cf6e935644a717e05d17f0c540db47683af AS git-stage
WORKDIR /repo
RUN git clone https://github.com/pagopa/selfcare-infra.git

FROM mcr.microsoft.com/azure-cli@sha256:18ec5cf02ba6b46e9858ddff1125baaa1f14ba919f77ebc67c918c891f8df4a2
COPY --from=git-stage /repo/selfcare-infra/src/core/resources /workspace/resources/resources
CMD ["/bin/sh", "-c", "/initAzurite.sh"]