apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: b4f-dashboard
  name: b4f-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b4f-dashboard
  template:
    metadata:
      labels:
        app: b4f-dashboard
    spec:
      containers:
        - name: b4f-dashboard
          image: selcdacr.azurecr.io/selfcaredashboardbackend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: application-insights
            - secretRef:
                name: b4f-dashboard
            - configMapRef:
                name: b4f-dashboard
            - configMapRef:
                name: inner-service-url
            - configMapRef:
                name: jwt-exchange
            - configMapRef:
                name: common
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
