apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dashboardbackend
  name: dashboardbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboardbackend
  template:
    metadata:
      labels:
        app: dashboardbackend
    spec:
      containers:
        - name: dashboardbackend
          image: selcpacr.azurecr.io/dashboardbackend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: application-insights
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
