/*
 * Party Management Micro Service
 * This service is the party manager
 *
 * OpenAPI spec version: 0.1
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pagopa.selfcare.dashboard.connector.model.organization;

import java.util.ArrayList;

/**
 * Attributes
 */
public class Attributes extends ArrayList<String> {
}
