/*
 * Party Process Micro Service
 * This service is the party process
 *
 * OpenAPI spec version: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pagopa.selfcare.dashboard.model.product;

import io.swagger.v3.oas.annotations.media.Schema;
import it.pagopa.selfcare.commons.base.security.SelfCareAuthority;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.UUID;

@Data
public class ProductUserResource {

    @Schema(description = "${swagger.dashboard.user.model.id}")
    private UUID id;

    @Schema(description = "${swagger.dashboard.user.model.name}")
    private String name;

    @Schema(description = "${swagger.dashboard.user.model.surname}")
    private String surname;

    @Schema(description = "${swagger.dashboard.user.model.fiscalCode}")
    private String fiscalCode;

    @Schema(description = "${swagger.dashboard.user.model.email}")
    private String email;

    @Schema(description = "${swagger.dashboard.user.model.selcRole}")
    private SelfCareAuthority role;

    @Schema(description = "${swagger.dashboard.user.model.product}")
    private ProductInfoResource product;

    @Schema(description = "${swagger.dashboard.user.model.status}")
    private String status;

    @Schema(description = "${swagger.dashboard.user.model.createdAt}")
    private LocalDateTime createdAt;


}
