/*
 * Party Process Micro Service
 * This service is the party process
 *
 * OpenAPI spec version: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pagopa.selfcare.dashboard.model;

import io.swagger.v3.oas.annotations.media.Schema;
import it.pagopa.selfcare.commons.base.security.SelfCareAuthority;
import it.pagopa.selfcare.dashboard.model.product.ProductInfoResource;
import lombok.Data;

import java.util.List;
import java.util.UUID;
@Data
public class InstitutionUserResource {

    @Schema(description = "${swagger.dashboard.user.model.id}")
    private UUID id;

    @Schema(description = "${swagger.dashboard.user.model.name}")
    private String name;

    @Schema(description = "${swagger.dashboard.user.model.surname}")
    private String surname;

    @Schema(description = "${swagger.dashboard.user.model.email}")
    private String email;

    @Schema(description = "${swagger.dashboard.user.model.institutionalPhone}")
    private String mobilePhone;

    @Schema(description = "${swagger.dashboard.user.model.role}")
    private SelfCareAuthority role;

    @Schema(description = "${swagger.dashboard.user.model.status}")
    private String status;

    @Schema(description = "${swagger.dashboard.user.model.products}")
    private List<ProductInfoResource> products;

}
