replicaCount: 2

image:
  repository: selcdacr.azurecr.io/selfcaredashboardbackend

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.selfcare.pagopa.it,http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:3003"
  tls:
    - hosts:
        - selc.internal.dev.selfcare.pagopa.it
      secretName: selc-internal-dev-selfcare-pagopa-it
  hosts:
    - host: selc.internal.dev.selfcare.pagopa.it
      paths:
        - path: /dashboard/(.*)
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 300m
    memory: 700M
  limits:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  B4F_DASHBOARD_LOG_LEVEL: "DEBUG"
  REST_CLIENT_LOGGER_LEVEL: "FULL"
  JWT_TOKEN_EXCHANGE_ISSUER: "https://dev.selfcare.pagopa.it"
  PUBLIC_FILE_STORAGE_BASE_URL: "https://selcdcheckoutsa.z6.web.core.windows.net"
  PAGO_PA_BACKOFFICE_URL: "https://api.dev.platform.pagopa.it/apiconfig/auth/api/v1"

