image:
  repository: selcuacr.azurecr.io/selfcareb4fdashboard
  tag: 0.0.1-SNAPSHOT

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  B4F_DASHBOARD_LOG_LEVEL: "INFO"
  REST_CLIENT_LOGGER_LEVEL: "BASIC"