/*
 * Party Process Micro Service
 * This service is the party process
 *
 * OpenAPI spec version: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.pagopa.selfcare.dashboard.connector.rest.model;

import it.pagopa.selfcare.dashboard.connector.model.user.Certification;
import it.pagopa.selfcare.dashboard.connector.model.user.InstitutionContact;
import lombok.Data;

import java.time.OffsetDateTime;
import java.util.Map;

@Data
public class RelationshipInfo {

    private String id;
    private String from;
    private String name;
    private String surname;
    private String email;
    private PartyRole role;
    private String taxCode;
    private Certification certification;
    private Map<String, InstitutionContact> institutionContacts;
    private ProductInfo product;
    private RelationshipState state;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

}
