name: Opex Dashboard api-pagopa-proxy

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - 'api-spec/api-pagopa-proxy.yaml'
      - '.github/workflows/opex_api.yml'
      - '.opex/api-selfcare-dashboard/**'
  workflow_dispatch:

env:
  TEMPLATE_DIR: azure-dashboard
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_CD }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  API_NAME: api-selfcare-dashboard
  DOCKER_IMAGE_TAG: sha256:04d8ead53c772d23b094c2a395292dc159e6f2905e1b13b5f828f31eac6eb27f

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    environment: 'prod-cd'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Read terraform version
        id: read-version
        shell: bash
        run: |
          echo "TERRAFORM_VERSION=`cat .terraform-version`" >> $GITHUB_ENV

      - name: Setup Terraform
        # from https://github.com/hashicorp/setup-terraform/commits/main
        uses: hashicorp/setup-terraform@69c00852f1304c321337f45a105731218c2d5544
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - uses: pagopa/opex-dashboard-azure-action@3ad80a5e4a2d5a8f342615637072f21b687320ce
        with:
          environment: prod
          api-name: ${{ env.API_NAME }}
          config: .opex/${{ env.API_NAME }}/env/prod/config.yaml
          client-id: ${{ secrets.AZURE_CLIENT_ID_CD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          docker-version: ${{ env.DOCKER_IMAGE_TAG }}
